### ISSUE TITLE
How to specify the weight of the downloaded teacher model without access to the Internet?  

### ISSUE THREAD

**Issue by wongyufei** [yoshitomo-matsubara/torchdistill#121]
![image](https://user-images.githubusercontent.com/50480952/123746407-2fbd2480-d8e4-11eb-9751-6795b297ab2a.png)

**Comment by yoshitomo-matsubara** [comment]
Hi @wongyufei,

You can specify the file path of checkpoint by editing `ckpt` in the yaml file.
Note that the object loaded from `ckpt` should be a `dict` that contains a key of `model` with model weights.
e.g., you can save model weights compatible with `torchdistill` in the following way:
```
import torch
from torchvision.models import mobilenet_v2
ckpt = dict()
classifier = mobilenet_v2(pretrained=True)
ckpt['model'] = classifier.state_dict()
torch.save(ckpt, './test_ckpt.pt')
```
and you can replace ckpt entry with `ckpt: './test_ckpt.pt'` under student_model/teacher_model of the yaml file
