### ISSUE TITLE
CSE-L2 KD  mobilenetv2 from resnet18 on cifar100 

### ISSUE THREAD

**Issue by wongyufei** [yoshitomo-matsubara/torchdistill#131]
I try to imply CSE-L2. student model is mobilenetv2 and teacher model is resnet18. The dataset is cifar10/100. Here are my problems.

(torchdistill) lthpc@lthpc:/data/Code/Wang_Yufei/PAD/torchdistill$ bash cifar100.sh
2021/07/04 19:16:30     INFO    torchdistill.common.main_util   Not using distributed mode
2021/07/04 19:16:30     INFO    __main__        Namespace(adjust_lr=False, config='configs/sample/cifar100/kd/L2-mobilenetv2_from_resnet_18-final_run.yaml', device='cuda', dist_url='env://', log='log/cifar100/kd/L2-mobilenetv2_from_resnet_18-final_run.log', seed=None, start_epoch=0, student_only=False, sync_bn=False, test_only=False, world_size=1)
2021/07/04 19:16:30     INFO    torchdistill.datasets.util      Loading train data
Files already downloaded and verified
2021/07/04 19:16:31     INFO    torchdistill.datasets.util      dataset_id `cifar100/train`: 0.9996764659881592 sec
2021/07/04 19:16:31     INFO    torchdistill.datasets.util      Loading val data
Files already downloaded and verified
2021/07/04 19:16:31     INFO    torchdistill.datasets.util      dataset_id `cifar100/val`: 0.6575329303741455 sec
2021/07/04 19:16:31     INFO    torchdistill.datasets.util      Loading test data
Files already downloaded and verified
2021/07/04 19:16:32     INFO    torchdistill.datasets.util      dataset_id `cifar100/test`: 0.6455981731414795 sec
2021/07/04 19:16:32     INFO    torchdistill.common.main_util   Loading model parameters
2021/07/04 19:16:36     INFO    torchdistill.common.main_util   ckpt file is not found at `./resource/ckpt/cifar100/L2/cifar100-mobilev2_from_resnet_18-final_run.pt`
2021/07/04 19:16:36     INFO    __main__        Start training
2021/07/04 19:16:36     INFO    torchdistill.models.util        [teacher model]
2021/07/04 19:16:36     INFO    torchdistill.models.util        Using the original teacher model
2021/07/04 19:16:36     INFO    torchdistill.models.util        [student model]
2021/07/04 19:16:36     INFO    torchdistill.models.util        Using the original student model
Traceback (most recent call last):
  File "examples/image_classification.py", line 180, in <module>
    main(argparser.parse_args())
  File "examples/image_classification.py", line 162, in main
    train(teacher_model, student_model, dataset_dict, ckpt_file_path, device, device_ids, distributed, config, args)
  File "examples/image_classification.py", line 110, in train
    device, device_ids, distributed, lr_factor)
  File "/data/Code/Wang_Yufei/PAD/torchdistill/torchdistill/core/distillation.py", line 406, in get_distillation_box
    device, device_ids, distributed, lr_factor, accelerator)
  File "/data/Code/Wang_Yufei/PAD/torchdistill/torchdistill/core/distillation.py", line 229, in __init__
    self.setup(train_config)
  File "/data/Code/Wang_Yufei/PAD/torchdistill/torchdistill/core/distillation.py", line 105, in setup
    self.setup_teacher_student_models(teacher_config, student_config)
  File "/data/Code/Wang_Yufei/PAD/torchdistill/torchdistill/core/distillation.py", line 82, in setup_teacher_student_models
    student_config, self.student_io_dict))
  File "/data/Code/Wang_Yufei/PAD/torchdistill/torchdistill/core/util.py", line 39, in set_hooks
    requires_input, requires_output, io_dict)
  File "/data/Code/Wang_Yufei/PAD/torchdistill/torchdistill/core/forward_hook.py", line 75, in register_forward_hook_with_dict
    return module.register_forward_hook(forward_hook4output)
AttributeError: 'function' object has no attribute 'register_forward_hook'
(torchdistill) lthpc@lthpc:/data/Code/Wang_Yufei/PAD/torchdistill$

Do you know the answers?

**Comment by yoshitomo-matsubara** [comment]
Hi @wongyufei ,
It seems your models were not properly instantiated. If your models are properly instantiated, it should be an instance of nn.Module, not function pointed out by `AttributeError: 'function' object has no attribute 'register_forward_hook'`

Could you provide 
1. a yaml file you used and
2. code if you modified,
assuming that you used `examples/image_classificaton.py` ?

Also, MobileNetV2 and ResNet-18 are both designed for ImageNet dataset and would not work with CIFAR datasets since the input size is much smaller (224x224 for ImageNet -> 32x32 for CIFAR-10/100). I'd suggest you use [some of models for CIFAR datasets shown here](https://github.com/yoshitomo-matsubara/torchdistill/releases/tag/v0.1.1) as teacher and student models instead

**Comment by wongyufei** [comment]
> Hi @wongyufei ,
> It seems your models were not properly instantiated. If your models are properly instantiated, it should be an instance of nn.Module, not function pointed out by `AttributeError: 'function' object has no attribute 'register_forward_hook'`
> 
> Could you provide
> 
> 1. a yaml file you used and
> 2. code if you modified,
>    assuming that you used `examples/image_classificaton.py` ?
> 
> Also, MobileNetV2 and ResNet-18 are both designed for ImageNet dataset and would not work with CIFAR datasets since the input size is much smaller (224x224 for ImageNet -> 32x32 for CIFAR-10/100). I'd suggest you use [some of models for CIFAR datasets shown here](https://github.com/yoshitomo-matsubara/torchdistill/releases/tag/v0.1.1) as teacher and student models instead

I guess I know the reason. Thanks for your reply!
