### ISSUE TITLE
Drop Fully Connected Layer of a Pretrained model

### ISSUE THREAD

**Issue by AhmedHussKhalifa** [yoshitomo-matsubara/torchdistill#168]
Hey, 
I was wondering if we can drop the fully connected layer for a pretrained model on ImageNet and fine-tune it. 

Is there any possibility to integrate your framework with the models mentioned in [this link](https://pytorch.org/vision/stable/models.html) or [here](https://github.com/Cadene/pretrained-models.pytorch) ?

**Comment by yoshitomo-matsubara** [comment]
Hi @AhmedHussKhalifa ,

The models in torchvision and PyTorch Hub are already supported, and you can use them by replacing model names (and parameters if necessary) in a yaml config
e.g., replace [`resnet152` in this line](https://github.com/yoshitomo-matsubara/torchdistill/blob/main/configs/sample/ilsvrc2012/single_stage/kd/resnet18_from_resnet152.yaml#L42) with `mobilenet_v3_large` to be used as a teacher 

Again, please use Discussions for asking questions and close #168 and #165 

Thank you
