### ISSUE TITLE
How to train my own COCO dataset for object detection?

### ISSUE THREAD

**Issue by Muke6** [yoshitomo-matsubara/torchdistill#222]
I encountered the following problem.
（1）

![微信截图_20220413222328](https://user-images.githubusercontent.com/89955551/163202527-45b64047-6109-47cd-acaf-69e410ae61e9.png)
（2）
How do I modify the number of categories?

**Comment by yoshitomo-matsubara** [comment]
Hi @Muke6 

Please use Discussions tab above for questions and close this issue.
As explained [here](https://github.com/yoshitomo-matsubara/torchdistill#issues--questions--requests), I want to keep Issues mainly for bug reports.
