### ISSUE TITLE
Use different models as Teacher/Student

### ISSUE THREAD

**Issue by jaideep11061982** [yoshitomo-matsubara/torchdistill#246]
@yoshitomo-matsubara @bot66 @dostos 

How i can use different models as teacher/student ,lets i want to  use teacher as Effnet b5 and student as Effnet b0

**Comment by yoshitomo-matsubara** [comment]
Hi @jaideep11061982 

Please use Discussions above (instead of Issues) for questions.
As explained [here](https://github.com/yoshitomo-matsubara/torchdistill#issues--questions--requests), I want to keep Issues mainly for bug reports.
