### ISSUE TITLE
Where is trained model?

### ISSUE THREAD

**Issue by Holmes2002** [yoshitomo-matsubara/torchdistill#259]
I had trained segmentation model, but i didn't find it.

**Comment by yoshitomo-matsubara** [comment]
Hi @Holmes2002 

If you're asking about the trained model weights, it is part of the checkpoint file you defined in your yaml file e.g., [`ckpt`](https://github.com/yoshitomo-matsubara/torchdistill/blob/main/configs/sample/pascal_voc2012/ce/deeplabv3_resnet50.yaml#L68)

If you need only the model weights, you can extract them from the checkpoint file by
```shell
python3 examples/params_extractor.py --src <your_ckpt_file_path> --keys model --dst <output_model_weights_file_path>
```

Close this discussion by selecting the reply as "answer" if it resolves your problem.
