### ISSUE TITLE
How should I use Torchdistill？

### ISSUE THREAD

**Issue by 2842193395** [yoshitomo-matsubara/torchdistill#365]
How should TorchdiStill be used in the project

**Comment by yoshitomo-matsubara** [comment]
This is not a bug or an issue either. 

Please use Discussions (Q&A) above (instead of Issues) for questions .
As explained [here](https://github.com/yoshitomo-matsubara/torchdistill#issues--questions--requests), I want to keep Issues mainly for bug reports.
