### ISSUE TITLE
[BUG]ImportError: cannot import name 'import_dependencies' from 'torchdistill.common.main_util' 

### ISSUE THREAD

**Issue by zhangruju** [yoshitomo-matsubara/torchdistill#398]
Hi,yoshitomo,I have a question about setting up a virtual environment.How can I resolve it?
**Describe the bug**
Traceback (most recent call last):
  File "H:/torchdistill/torchdistill-main/examples/torchvision/image_classification.py", line 14, in <module>
    from torchdistill.common.main_util import is_main_process, init_distributed_mode, load_ckpt, save_ckpt, set_seed, \
ImportError: cannot import name 'import_dependencies' from 'torchdistill.common.main_util' (E:\Anaconda\envs\torchdistill\lib\site-packages\torchdistill\common\main_util.py)

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]
 - Python ver.  3.8
 - torchdistill ver. v0.3.3
 - torch==1.8.0+cu111 torchvision==0.9.0+cu111

**Comment by yoshitomo-matsubara** [comment]
Hi @zhangruju 

This is not a bug. 
Please read https://github.com/yoshitomo-matsubara/torchdistill#important-notice

**Comment by zhangruju** [comment]
Thank you very much.



在 2023-09-10 23:32:44，"Yoshitomo Matsubara" ***@***.***> 写道：

Closed #398 as completed.
