### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'torch._six'

### ISSUE THREAD

**Issue by nirgoren** [yoshitomo-matsubara/torchdistill#448]
**Bug description**
When trying to import `torchdistill.core.forward_hook` with an up-to-date version of pytorch, you get `ModuleNotFoundError: No module named 'torch._six'` error.

**To Reproduce**
1. Exact command to run your code: `import torchdistill.core.forward_hook`
2. Whether or not you made any changes in Python code (if so, how you made the changes?): Did not make changes.
3. YAML config file - not relevant.
4. Log file - not relevant.

**Expected behavior**
The import should succeed without errors.

**Environment:**
 - OS: Ubuntu 22.04 LTS
 - Python ver. 3.12.2
 - torchdistill ver. v0.3.3
 - torch ver. v2.2.1

**Additional context**
Related to this change in pytorch: https://github.com/pytorch/pytorch/pull/94709
Apparently `string_classes` is no longer needed and `str` can be used instead.

**Comment by yoshitomo-matsubara** [comment]
Hi @nirgoren ,

You're an old version of torchdistill. It is already resolved in torchdistill v1.0.0

**Comment by nirgoren** [comment]
> Hi @nirgoren ,
> 
> You're an old version of torchdistill. It is already resolved in torchdistill v1.0.0

I see. Note that pip automatically downloaded v0.3.3 for me due to having torch v2.2.1 installed and v1.0.0 of torchdistill requiring a version of torch that is `<=2.1.0`. It would be nice to have compatibility with the latest version of torch, if that doesn't cause any issues.

**Comment by yoshitomo-matsubara** [comment]
You could still use torchdistill v1.0.0 with the latest torch if you force-install torchdistill though I've not tested it.

From torchdistill v1.0.0, I started specifying min/max versions of key requirements to avoid the same mistakes as the old torchdistill had e.g., torchdistill v0.3.3.

Next release of torchdistill with the latest torch support is around the corner, probably next week. Stay tune!
