### ISSUE TITLE
[BUG] Problems in DistillationBox

### ISSUE THREAD

**Issue by 1396066796** [yoshitomo-matsubara/torchdistill#471]
Please use [Discussions](https://github.com/yoshitomo-matsubara/torchdistill/discussions) to ask questions.

**Describe the bug**
[A clear and concise description of what the bug is.](https://github.com/yoshitomo-matsubara/torchdistill/blob/f1e7db8c152468710f4a67cb98614fe6314ded3c/torchdistill/core/distillation.py#L417)

In DistillationBox, the class instantiates the AuxiliaryModelWrapper before placing the model in DataParallel. I am attaching a screenshot below.

**To Reproduce**
Provide
Whether or not you made any changes in Python code (if so, how you made the changes?)  none lib file changed
Project files
[srd.zip](https://github.com/yoshitomo-matsubara/torchdistill/files/15445661/srd.zip)

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [Ubuntu 20.04 LTS]
 - Python ver. [3.9]
 - torchdistill ver. [lasted]

**Additional context**
![ef74033aaf1b388412b6734623947a4](https://github.com/yoshitomo-matsubara/torchdistill/assets/170806620/94ab7377-0306-4651-b7c8-6b943dd99f6a)

![754c85d6e5ad615a2a6eaa869a184fe](https://github.com/yoshitomo-matsubara/torchdistill/assets/170806620/26ff4899-e7c4-4da9-b864-d999aac04b48)

![f6e33c006bd1bc47be3601bcee7c2ea](https://github.com/yoshitomo-matsubara/torchdistill/assets/170806620/e9713d85-5c9d-4e60-8acf-2dfb3e0d0575)

![065d4f5039b1ff9dedbaa6daea58710](https://github.com/yoshitomo-matsubara/torchdistill/assets/170806620/8d377a0c-cf05-49f8-b713-009fc33c3c42)

**Comment by yoshitomo-matsubara** [comment]
Hi @1396066796 

Thank you for the issue.
The `AuxiliaryModelWrapper` should be wrapped by `wrapper: DataParallel`, and it looks like the config is incorrect. I'm fixing it now

**Comment by yoshitomo-matsubara** [comment]
It is not a bug in code, but in the config file. I updated the sample config file in the above PR.
For the official SRD config, I will work with @roymiles in a separate PR
